const data = [
  {
    id: 1,
    image: "./sweets/Mewa-Bite.jpg",
    name: "Mewa Burfi",
    price: 700,
    discount_price: 1000,
    rating: 5,
    quantity: 1,
    total: "700",
  },
  {
    id: 2,
    image: "./sweets/milk-peda.jpg",
    name: "Milk Peda",
    price: 900,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "900",
  },
  {
    id: 3,
    image: "./sweets/Kaju-Burfi.jpg",
    name: "Kaju Burfi",
    price: 800,
    discount_price: 1100,
    rating: 4,
    quantity: 1,
    total: "800",
  },
  {
    id: 4,
    image: "./sweets/Mewa-Binni.jpg",
    name: "Mewa Ladoo",
    price: 600,
    discount_price: 1050,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 5,
    image: "./sweets/baby-gujiya.jpg",
    name: "Baby Gujiya",
    price: 650,
    discount_price: 1050,
    rating: 5,
    quantity: 1,
    total: "650",
  },
  {
    id: 6,
    image: "./sweets/Choco-Almond.jpg",
    name: "Khoya Burfi",
    price: 550,
    discount_price: 900,
    rating: 4,
    quantity: 1,
    total: "550",
  },
  {
    id: 7,
    image: "./sweets/Mewa-Bite.jpg",
    name: "Diwali Burfi",
    price: 740,
    discount_price: 1100,
    rating: 4,
    quantity: 1,
    total: "740",
  },
  {
    id: 8,
    image: "./sweets/Anjeer-Roll.jpg",
    name: "Kaaju Kalash",
    price: 850,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 9,
    image: "./sweets/sugarfree.jpg",
    name: "Sugarfree",
    price: 490,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 10,
    image: "./sweets/Batisa-Slice.jpg",
    name: "Batisa Burfi",
    price: 350,
    discount_price: 1200,
    rating: 3,
    quantity: 1,
    total: "850",
  },
  {
    id: 11,
    image: "./sweets/Coconutty.jpg",
    name: "Coconut Peda",
    price: 850,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 12,
    image: "./sweets/Kesariya-Peda.jpg",
    name: "Kesariya Peda",
    price: 750,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 13,
    image: "./sweets/soan-papdi.jpg",
    name: "Soan Papdi",
    price: 400,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 14,
    image: "./sweets/combo-pack.jpg",
    name: "Combo Pack",
    price: 850,
    discount_price: 1200,
    rating: 3,
    quantity: 1,
    total: "850",
  },
  {
    id: 15,
    image: "./sweets/combo-pack1.jpg",
    name: "Combo Pack",
    price: 950,
    discount_price: 1200,
    rating: 5,
    quantity: 1,
    total: "850",
  },
  {
    id: 16,
    image: "./sweets/combo.jpg",
    name: "Combo Pack",
    price: 850,
    discount_price: 1200,
    rating: 3,
    quantity: 1,
    total: "850",
  },
];
export default data;
